version: '3.8'


services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - learning-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  mysql-db:
    image: mysql:8.0
    container_name: learning-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: learning_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - learning-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_SERVER_URL}
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - learning-network
    restart: on-failure

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_SERVER_URL}
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - learning-network
    restart: on-failure

  learning-service:
    build: exam-service
    container_name: learning-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_SERVER_URL}
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - learning-network
    restart: on-failure

volumes:
  mysql_data:

networks:
  learning-network:
    driver: bridge
