server:
  port: 8082

spring:
  application:
    name: exam-service
  datasource:
    url: jdbc:mysql://localhost:3306/learning_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: mypassword1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

jwt:
  expiration: 86400000
  secret: dGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1zZWNyZXQta2V5LWZvci1oczM4NC1hbGdvcml0aG0tdGhhdC1pcy1sb25nLWVub3VnaC0xMjM=
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2.jwt: TRACE
    org.springframework.security.web: DEBUG